// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlFtus4STi76KzO8mKNea9bHeP1YZZQqU',
    appId: '1:20404282117:web:2e955ee7a5b05ca8e8cd6c',
    messagingSenderId: '20404282117',
    projectId: 'barlab-66741',
    authDomain: 'barlab-66741.firebaseapp.com',
    storageBucket: 'barlab-66741.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM87cW8XpbWIgoprgfr3aWkElT0I-_AZM',
    appId: '1:20404282117:android:c92ab5df1efb51b6e8cd6c',
    messagingSenderId: '20404282117',
    projectId: 'barlab-66741',
    storageBucket: 'barlab-66741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPlUs9QIu89yUNqC7v8HachncQIxXuexs',
    appId: '1:20404282117:ios:a75fbbe26f3a8bd2e8cd6c',
    messagingSenderId: '20404282117',
    projectId: 'barlab-66741',
    storageBucket: 'barlab-66741.appspot.com',
    iosClientId: '20404282117-oq3hrmlgi2md1ag7o70jgeovugt2gr2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.barlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPlUs9QIu89yUNqC7v8HachncQIxXuexs',
    appId: '1:20404282117:ios:48e4f884f9712324e8cd6c',
    messagingSenderId: '20404282117',
    projectId: 'barlab-66741',
    storageBucket: 'barlab-66741.appspot.com',
    iosClientId: '20404282117-ddi4v771in72i0ihfk0uag1o3t7irsvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.barlab.RunnerTests',
  );
}
